version: "3.4"

services:
    # front
    episen-sca-mco-front :
        build : ./episen-sca-mco-front/ .
        container_name : happy_knuth
        restart: always
        volumes: 
            - 'C:\Users\mb601\Documents\GitHub\ing3-sca-tp3-mco\episen-sca-mco-front\frontend:/var/log/nginx'
        ports : 
            - 80:80
        healthcheck:
            test: ["CMD", "curl -f http://localhost:80 || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5            
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: '0.5'
                    memory: 300m
                reservations:
                    cpus: '0.5'
                    memory: 100m
                        
    # back
    episen-sca-mco-back :
        build: ./episen-sca-mco-back/ .
        container_name: sad_mestorf
        restart: always
        volumes: 
            - 'C:\Users\mb601\Documents\GitHub\ing3-sca-tp3-mco\episen-sca-mco-back\backend:/logs'
            - 'C:\Users\mb601\Documents\GitHub\ing3-sca-tp3-mco\episen-sca-mco-back\orders:/orders'
        ports : 
            - 8080:8080
        healthcheck:
            test: ["CMD", "curl -f http://localhost:8080 || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5 
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: '0.5'
                    memory: 300m
                reservations:
                    cpus: '0.5'
                    memory: 100m
                    
        